### ISSUE TITLE
Create package.json file

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/LeQue#274]
Each project implementing grunt must have a `package.json` file

**Comment by jeff1evesque** [comment]
```
$ cd /var/www/audio-analyzer
$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sane defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (audio-analyzer) Audio Analyzer
version: (0.0.0) 
description: This program converts audio to text
entry point: (gruntfile.js) 
test command: 
git repository: (https://jeff1evesque@github.com/jeff1evesque/audio-analyzer.git) 
keywords: CMUSphinx, PocketSphinx, audio translation
author: Jeffrey M. Levesque
license: (BSD-2-Clause) 
npm ERR! Error: Invalid name: "Audio Analyzer"
npm ERR!     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:297:15)
npm ERR!     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/fixer.js:201:5)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:29:38
npm ERR!     at Array.forEach (native)
npm ERR!     at normalize (/usr/local/lib/node_modules/npm/node_modules/read-package-json/node_modules/normalize-package-data/lib/normalize.js:28:15)
npm ERR!     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:310:33)
npm ERR!     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:33)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:299:40
npm ERR!     at fs.js:266:14
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/isaacs/npm/issues>

npm ERR! System Linux 2.6.38-8-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "init"
npm ERR! cwd /var/www/audio-analyzer
npm ERR! node -v v0.10.23
npm ERR! npm -v 1.3.17
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/audio-analyzer/npm-debug.log
npm ERR! not ok code 0

```

**Comment by jeff1evesque** [comment]
First we create the _package.json_ file:

```
$ cd /var/www/audio-analyzer
$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sane defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
name: (audio-analyzer) audio-analyzer
version: (0.0.0) 0.0.0
description: Activates installed microphone, and analyzes sound input
entry point: (gruntfile.js) gruntfile.js
test command: 
git repository: (https://jeff1evesque@github.com/jeff1evesque/audio-analyzer.git) 
keywords: CMUSphinx, PocketSphinx
author: Jeffrey M. Levesque
license: (BSD-2-Clause) 
About to write to /var/www/audio-analyzer/package.json:

{
  "name": "audio-analyzer",
  "version": "0.0.0",
  "description": "Activates installed microphone, and analyzes sound input",
  "main": "gruntfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://jeff1evesque@github.com/jeff1evesque/audio-analyzer.git"
  },
  "keywords": [
    "CMUSphinx",
    "PocketSphinx"
  ],
  "author": "Jeffrey M. Levesque",
  "license": "BSD-2-Clause",
  "bugs": {
    "url": "https://github.com/jeff1evesque/audio-analyzer/issues"
  },
  "homepage": "https://github.com/jeff1evesque/audio-analyzer"
}
```

**IRC #node.js (07/06/14 ~ 9:30pm EST):**

```
zbzzn:  yeah, you can't name stuff with spaces
zbzzn:  like in github
jeffreylevesque:  got it
zbzzn:  in brackets is suggests default values, try to stick with those
jeffreylevesque:  do i need to fill in every field?
zbzzn   just name and version
```

**Comment by jeff1evesque** [comment]
Then, we install our _grunt_ plugins.  This is done per-project (web application):

```
$ npm install grunt --save-dev
npm http GET https://registry.npmjs.org/grunt
npm http 200 https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
npm http 200 https://registry.npmjs.org/grunt/-/grunt-0.4.5.tgz
npm http GET https://registry.npmjs.org/eventemitter2
npm http GET https://registry.npmjs.org/hooker
npm http GET https://registry.npmjs.org/findup-sync
npm http GET https://registry.npmjs.org/iconv-lite
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/which
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/exit
npm http GET https://registry.npmjs.org/getobject
npm http GET https://registry.npmjs.org/grunt-legacy-util
npm http GET https://registry.npmjs.org/grunt-legacy-log
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http 304 https://registry.npmjs.org/hooker
npm http 304 https://registry.npmjs.org/iconv-lite
npm http 304 https://registry.npmjs.org/minimatch
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/eventemitter2
npm http 304 https://registry.npmjs.org/findup-sync
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/which
npm http 304 https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/exit
npm http 304 https://registry.npmjs.org/getobject
npm http 304 https://registry.npmjs.org/grunt-legacy-util
npm http 304 https://registry.npmjs.org/grunt-legacy-log
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm http GET https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore
grunt@0.4.5 node_modules/grunt
├── which@1.0.5
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── nopt@1.0.10 (abbrev@1.0.5)
├── exit@0.1.2
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)
├── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.15)
└── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)
```

Similarly, we execute the following commands:

```
npm install grunt-contrib-sass --save-dev
npm install grunt-contrib-watch --save-dev
```

**Comment by jeff1evesque** [comment]
Now, we will have a new directory with the following elements:

```
$ cd /var/www/audio-analyzer/node_modules
$ ls
grunt  grunt-contrib-sass  grunt-contrib-watch
```

**Comment by jeff1evesque** [comment]
An alternative method to installing each grunt plug-in locally, for example:

```
$ npm install grunt-contrib-sass --save-dev
```

We can simply clone https://github.com/jeff1evesque/grunt into this project, and create the `package.json` within the cloned directory as [we did above](https://github.com/jeff1evesque/audio-analyzer/issues/274#issuecomment-48112031).
